name: Vercel Preview URL
on: [pull_request]
jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Vercel Preview URL
        id: vercel
        uses: zentered/vercel-preview-url@v1.1.9
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
      - name: Comment URL on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          message: |
            🚀 Preview: ${{ steps.vercel.outputs.preview_url }}
            _(auto-updates as you push new commits)_
